import "../globals.css";
import Navbar from "@/components/adminDashboard/navbar/Navbar";

export const metadata = {
	title: "EPK | Admin Panel",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" dir="rtl">
			<body className="flex">
				<Navbar />
				{children}
			</body>
		</html>
	);
}
